### ISSUE TITLE
Firewall is enabled but not managed

### ISSUE THREAD

**Issue by silug** [puppet-bootstrap/basic-aio#6]
Any additional VMs added to the Vagrantfile can't talk to the Puppet server due to firewall rules.

There doesn't appear to be an obvious solution for this.  [puppetlabs/puppetdb](https://forge.puppet.com/puppetlabs/puppetdb) pulls in [puppetlabs/firewall](https://forge.puppet.com/puppetlabs/firewall), which seems to turn on the `iptables` service with default rules.  puppetlabs/firewall doesn't support rules in hiera (which would be the obvious solution).  This leaves us with 2 options (that I can see):

1. Add in some other firewall module (and hope they don't conflict) plus hiera options.
2. Include a simple module that creates the firewall rules.

**Comment by jaevans** [comment]
For 1, I've looked at crayfishx/firewalld, but haven't actually worked with it yet.
We'll have to set `puppetdb::manage_firewall` to false. 

There's also always:
3. Disable the firewall

I'd rather get firewalld working than do that.

**Comment by silug** [comment]
If setting `puppetdb::manage_firewall` is an option, I'd say that's the simplest answer for now.

I've used `crayfishx/firewalld`.  It's simple.  That is probably the right answer long-term if we want to demonstrate best practices.

**Comment by silug** [comment]
#12 disables the firewall entirely.

Leaving this open as a reminder to actually manage the firewall.
